### ISSUE TITLE
Documentation / README.md Sucks

### ISSUE THREAD

**Issue by dokbua** [Nold360/borgserver#10]
The documentation is inconsistent about directories, sometimes referring to _borg/sshkeys/clients_, other times just _sshkeys/clients_. Same with _borg/backup_ and just _backup_.

**Comment by Nold360** [comment]
I guess this will be addressed with borgserver:v2, which will [most likely] store the pubkeys in git. Besides that you're right. Feel free to create a PR.

**Comment by dokbua** [comment]
Cheers. Let me first understand this, then I might.
