### ISSUE TITLE
Have a way to specify sshd_config options

### ISSUE THREAD

**Issue by alkim0** [Nold360/borgserver#18]
Thanks for your work. I use it all the time.

It would be nice to have a way to specify `sshd_config` options to follow the recommendation in the [borg documentation](https://borgbackup.readthedocs.io/en/stable/usage/serve.html#ssh-configuration). If it undesirable to add general `sshd_config` options, just having a way to specify:
```
ClientAliveInterval 10
ClientAliveCountMax 30
```
would be good.

Thanks.

**Comment by Nold360** [comment]
Thanks for your issue.

I would be willing to add these parameters to the default `sshd_config`, but you can still mount your own config into the container like this:
```yaml
volumes:
  - path/to/sshd_config:/etc/ssh/sshd_config:ro
```

**Comment by alkim0** [comment]
Doh! Good point.
