### ISSUE TITLE
docker-compose.yml example is incomplete

### ISSUE THREAD

**Issue by dokbua** [Nold360/borgserver#9]
First line in a docker-compose.yml file needs to be a version number, i.e.

`version: "3"`

**Comment by Nold360** [comment]
you mean like this: https://github.com/Nold360/docker-borgserver/blob/ac797c90f66f19e9b130ddae482932e7e4e3d5b5/docker-compose.yml#L1 ?

**Comment by Nold360** [comment]
oh, in the README.. alright.
